create extension if not exists "pgjwt" with schema "extensions";

drop extension if exists "pg_net";


  create table "public"."absentees" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "session_id" bigint,
    "student_id" uuid,
    "reason" text
      );


alter table "public"."absentees" enable row level security;


  create table "public"."active_sessions" (
    "id" bigint generated by default as identity not null,
    "session_id" bigint not null,
    "student_id" uuid not null,
    "joined_at" timestamp with time zone not null default now()
      );


alter table "public"."active_sessions" enable row level security;


  create table "public"."channel_members" (
    "id" bigint generated by default as identity not null,
    "channel_id" uuid not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone default now()
      );



  create table "public"."channel_users" (
    "channel_id" uuid not null,
    "user_id" uuid not null
      );



  create table "public"."channels" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "name" text not null,
    "created_at" timestamp with time zone default now(),
    "imageUrl" text
      );


alter table "public"."channels" enable row level security;


  create table "public"."classes" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "grade" text,
    "manager_id" uuid,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."classes" enable row level security;


  create table "public"."exam_attempts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "student_id" uuid not null,
    "exam_id" bigint not null,
    "started_at" timestamp with time zone not null default now(),
    "finished_at" timestamp with time zone,
    "score" numeric(5,2)
      );


alter table "public"."exam_attempts" enable row level security;


  create table "public"."exams" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "exam_date" date not null,
    "created_at" timestamp with time zone default now(),
    "manager_id" uuid,
    "duration_minutes" integer,
    "class_id" uuid,
    "subject_id" bigint
      );


alter table "public"."exams" enable row level security;


  create table "public"."messages" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "channel_id" uuid not null,
    "content" text not null,
    "sender_id" uuid,
    "created_at" timestamp with time zone default now(),
    "imageUrl" text,
    "senderName" text,
    "senderAvatarUrl" text
      );


alter table "public"."messages" enable row level security;


  create table "public"."online_sessions" (
    "id" uuid not null default gen_random_uuid(),
    "title" text not null,
    "class_id" uuid,
    "session_days" text[] not null,
    "session_time" time without time zone not null,
    "meeting_id" text not null,
    "is_active" boolean default false,
    "created_by" uuid,
    "manager_id" uuid,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."online_sessions" enable row level security;


  create table "public"."pomodoro_sessions" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "user_id" uuid not null,
    "session_date" date default CURRENT_DATE,
    "start_time" timestamp with time zone default now(),
    "end_time" timestamp with time zone,
    "session_type" text,
    "duration_minutes" integer not null,
    "completed" boolean default false,
    "focus_duration_setting" integer not null,
    "break_duration_setting" integer not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."pomodoro_sessions" enable row level security;


  create table "public"."presence_checks" (
    "id" bigint generated always as identity not null,
    "session_id" uuid,
    "student_id" uuid,
    "responded" boolean default false,
    "is_entry" boolean default false,
    "expires_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."presence_checks" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "username" text,
    "name" text,
    "email" text,
    "avatar_url" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "filter" text,
    "role" text,
    "full_name" text,
    "father_name" text,
    "mother_name" text,
    "father_phone" text,
    "mother_phone" text,
    "home_phone" text,
    "description" text,
    "class" text,
    "grade" text,
    "field_of_study" text,
    "consultant_id" uuid,
    "school_name" text,
    "student_limit" integer,
    "manager_id" uuid,
    "class_id" uuid
      );


alter table "public"."profiles" enable row level security;


  create table "public"."questions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "exam_id" bigint not null,
    "question_text" text not null,
    "options" jsonb not null,
    "correct_option" text not null,
    "image_url" text
      );


alter table "public"."questions" enable row level security;


  create table "public"."scores" (
    "id" bigint generated by default as identity not null,
    "exam_id" bigint,
    "student_id" uuid,
    "score" numeric(5,2) not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."scores" enable row level security;


  create table "public"."settings" (
    "key" text not null,
    "value" text
      );



  create table "public"."student_answers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "student_id" uuid not null,
    "question_id" bigint not null,
    "chosen_option" text not null,
    "is_correct" boolean not null,
    "exam_id" bigint
      );


alter table "public"."student_answers" enable row level security;


  create table "public"."subjects" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone default now(),
    "manager_id" uuid
      );


alter table "public"."subjects" enable row level security;


  create table "public"."subscriptions" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "start_date" timestamp with time zone,
    "end_date" timestamp with time zone,
    "plan_type" text,
    "created_at" timestamp with time zone not null default now()
      );



  create table "public"."task_feedback" (
    "id" uuid not null default gen_random_uuid(),
    "task_id" uuid not null,
    "user_id" uuid not null,
    "feedback" text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."task_feedback" enable row level security;


  create table "public"."tasks" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "title" text not null,
    "date" text not null,
    "time_start" text,
    "time_end" text,
    "color" text not null,
    "is_completed" boolean default false,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "user_id" text,
    "class_id" uuid
      );


alter table "public"."tasks" enable row level security;


  create table "public"."users" (
    "id" uuid not null,
    "username" text,
    "name" text,
    "email" text,
    "avatar_url" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX absentees_pkey ON public.absentees USING btree (id);

CREATE UNIQUE INDEX active_sessions_pkey ON public.active_sessions USING btree (id);

CREATE UNIQUE INDEX active_sessions_session_id_student_id_key ON public.active_sessions USING btree (session_id, student_id);

CREATE UNIQUE INDEX channel_members_channel_id_user_id_key ON public.channel_members USING btree (channel_id, user_id);

CREATE UNIQUE INDEX channel_members_pkey ON public.channel_members USING btree (id);

CREATE UNIQUE INDEX channel_users_pkey ON public.channel_users USING btree (channel_id, user_id);

CREATE UNIQUE INDEX channels_pkey ON public.channels USING btree (id);

CREATE UNIQUE INDEX classes_pkey ON public.classes USING btree (id);

CREATE UNIQUE INDEX exam_attempts_pkey ON public.exam_attempts USING btree (id);

CREATE UNIQUE INDEX exams_pkey ON public.exams USING btree (id);

CREATE INDEX messages_channel_id_idx ON public.messages USING btree (channel_id);

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

CREATE UNIQUE INDEX online_sessions_meeting_id_key ON public.online_sessions USING btree (meeting_id);

CREATE UNIQUE INDEX online_sessions_pkey ON public.online_sessions USING btree (id);

CREATE UNIQUE INDEX pomodoro_sessions_pkey ON public.pomodoro_sessions USING btree (id);

CREATE INDEX pomodoro_sessions_user_date_idx ON public.pomodoro_sessions USING btree (user_id, session_date);

CREATE UNIQUE INDEX presence_checks_pkey ON public.presence_checks USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.users USING btree (id);

CREATE UNIQUE INDEX profiles_pkey1 ON public.profiles USING btree (id);

CREATE UNIQUE INDEX questions_pkey ON public.questions USING btree (id);

CREATE UNIQUE INDEX scores_exam_id_student_id_key ON public.scores USING btree (exam_id, student_id);

CREATE UNIQUE INDEX scores_pkey ON public.scores USING btree (id);

CREATE UNIQUE INDEX settings_pkey ON public.settings USING btree (key);

CREATE UNIQUE INDEX student_answers_pkey ON public.student_answers USING btree (id);

CREATE UNIQUE INDEX subjects_pkey ON public.subjects USING btree (id);

CREATE UNIQUE INDEX subscriptions_pkey ON public.subscriptions USING btree (id);

CREATE UNIQUE INDEX subscriptions_user_id_key ON public.subscriptions USING btree (user_id);

CREATE UNIQUE INDEX task_feedback_pkey ON public.task_feedback USING btree (id);

CREATE UNIQUE INDEX tasks_pkey ON public.tasks USING btree (id);

CREATE UNIQUE INDEX unique_student_exam ON public.exam_attempts USING btree (student_id, exam_id);

alter table "public"."absentees" add constraint "absentees_pkey" PRIMARY KEY using index "absentees_pkey";

alter table "public"."active_sessions" add constraint "active_sessions_pkey" PRIMARY KEY using index "active_sessions_pkey";

alter table "public"."channel_members" add constraint "channel_members_pkey" PRIMARY KEY using index "channel_members_pkey";

alter table "public"."channel_users" add constraint "channel_users_pkey" PRIMARY KEY using index "channel_users_pkey";

alter table "public"."channels" add constraint "channels_pkey" PRIMARY KEY using index "channels_pkey";

alter table "public"."classes" add constraint "classes_pkey" PRIMARY KEY using index "classes_pkey";

alter table "public"."exam_attempts" add constraint "exam_attempts_pkey" PRIMARY KEY using index "exam_attempts_pkey";

alter table "public"."exams" add constraint "exams_pkey" PRIMARY KEY using index "exams_pkey";

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."online_sessions" add constraint "online_sessions_pkey" PRIMARY KEY using index "online_sessions_pkey";

alter table "public"."pomodoro_sessions" add constraint "pomodoro_sessions_pkey" PRIMARY KEY using index "pomodoro_sessions_pkey";

alter table "public"."presence_checks" add constraint "presence_checks_pkey" PRIMARY KEY using index "presence_checks_pkey";

alter table "public"."profiles" add constraint "profiles_pkey1" PRIMARY KEY using index "profiles_pkey1";

alter table "public"."questions" add constraint "questions_pkey" PRIMARY KEY using index "questions_pkey";

alter table "public"."scores" add constraint "scores_pkey" PRIMARY KEY using index "scores_pkey";

alter table "public"."settings" add constraint "settings_pkey" PRIMARY KEY using index "settings_pkey";

alter table "public"."student_answers" add constraint "student_answers_pkey" PRIMARY KEY using index "student_answers_pkey";

alter table "public"."subjects" add constraint "subjects_pkey" PRIMARY KEY using index "subjects_pkey";

alter table "public"."subscriptions" add constraint "subscriptions_pkey" PRIMARY KEY using index "subscriptions_pkey";

alter table "public"."task_feedback" add constraint "task_feedback_pkey" PRIMARY KEY using index "task_feedback_pkey";

alter table "public"."tasks" add constraint "tasks_pkey" PRIMARY KEY using index "tasks_pkey";

alter table "public"."users" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."absentees" add constraint "absentees_student_id_fkey" FOREIGN KEY (student_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."absentees" validate constraint "absentees_student_id_fkey";

alter table "public"."active_sessions" add constraint "active_sessions_session_id_student_id_key" UNIQUE using index "active_sessions_session_id_student_id_key";

alter table "public"."active_sessions" add constraint "active_sessions_student_id_fkey" FOREIGN KEY (student_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."active_sessions" validate constraint "active_sessions_student_id_fkey";

alter table "public"."channel_members" add constraint "channel_members_channel_id_fkey" FOREIGN KEY (channel_id) REFERENCES public.channels(id) ON DELETE CASCADE not valid;

alter table "public"."channel_members" validate constraint "channel_members_channel_id_fkey";

alter table "public"."channel_members" add constraint "channel_members_channel_id_user_id_key" UNIQUE using index "channel_members_channel_id_user_id_key";

alter table "public"."channel_members" add constraint "channel_members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."channel_members" validate constraint "channel_members_user_id_fkey";

alter table "public"."channel_users" add constraint "channel_users_channel_id_fkey" FOREIGN KEY (channel_id) REFERENCES public.channels(id) not valid;

alter table "public"."channel_users" validate constraint "channel_users_channel_id_fkey";

alter table "public"."channel_users" add constraint "channel_users_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) not valid;

alter table "public"."channel_users" validate constraint "channel_users_user_id_fkey";

alter table "public"."classes" add constraint "classes_manager_id_fkey" FOREIGN KEY (manager_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."classes" validate constraint "classes_manager_id_fkey";

alter table "public"."exam_attempts" add constraint "exam_attempts_exam_id_fkey" FOREIGN KEY (exam_id) REFERENCES public.exams(id) ON DELETE CASCADE not valid;

alter table "public"."exam_attempts" validate constraint "exam_attempts_exam_id_fkey";

alter table "public"."exam_attempts" add constraint "exam_attempts_student_id_fkey" FOREIGN KEY (student_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."exam_attempts" validate constraint "exam_attempts_student_id_fkey";

alter table "public"."exam_attempts" add constraint "unique_student_exam" UNIQUE using index "unique_student_exam";

alter table "public"."exams" add constraint "exams_class_id_fkey" FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE CASCADE not valid;

alter table "public"."exams" validate constraint "exams_class_id_fkey";

alter table "public"."exams" add constraint "exams_manager_id_fkey" FOREIGN KEY (manager_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."exams" validate constraint "exams_manager_id_fkey";

alter table "public"."exams" add constraint "exams_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES public.subjects(id) ON DELETE CASCADE not valid;

alter table "public"."exams" validate constraint "exams_subject_id_fkey";

alter table "public"."messages" add constraint "messages_channel_id_fkey" FOREIGN KEY (channel_id) REFERENCES public.channels(id) ON DELETE CASCADE not valid;

alter table "public"."messages" validate constraint "messages_channel_id_fkey";

alter table "public"."online_sessions" add constraint "online_sessions_class_id_fkey" FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE CASCADE not valid;

alter table "public"."online_sessions" validate constraint "online_sessions_class_id_fkey";

alter table "public"."online_sessions" add constraint "online_sessions_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL not valid;

alter table "public"."online_sessions" validate constraint "online_sessions_created_by_fkey";

alter table "public"."online_sessions" add constraint "online_sessions_manager_id_fkey" FOREIGN KEY (manager_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."online_sessions" validate constraint "online_sessions_manager_id_fkey";

alter table "public"."online_sessions" add constraint "online_sessions_meeting_id_key" UNIQUE using index "online_sessions_meeting_id_key";

alter table "public"."pomodoro_sessions" add constraint "pomodoro_sessions_session_type_check" CHECK ((session_type = ANY (ARRAY['focus'::text, 'break'::text]))) not valid;

alter table "public"."pomodoro_sessions" validate constraint "pomodoro_sessions_session_type_check";

alter table "public"."pomodoro_sessions" add constraint "pomodoro_sessions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."pomodoro_sessions" validate constraint "pomodoro_sessions_user_id_fkey";

alter table "public"."presence_checks" add constraint "presence_checks_session_id_fkey" FOREIGN KEY (session_id) REFERENCES public.online_sessions(id) ON DELETE CASCADE not valid;

alter table "public"."presence_checks" validate constraint "presence_checks_session_id_fkey";

alter table "public"."presence_checks" add constraint "presence_checks_student_id_fkey" FOREIGN KEY (student_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."presence_checks" validate constraint "presence_checks_student_id_fkey";

alter table "public"."profiles" add constraint "profiles_class_id_fkey" FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE SET NULL not valid;

alter table "public"."profiles" validate constraint "profiles_class_id_fkey";

alter table "public"."profiles" add constraint "profiles_consultant_id_fkey" FOREIGN KEY (consultant_id) REFERENCES public.profiles(id) ON DELETE SET NULL not valid;

alter table "public"."profiles" validate constraint "profiles_consultant_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey1" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey1";

alter table "public"."profiles" add constraint "profiles_manager_id_fkey" FOREIGN KEY (manager_id) REFERENCES public.profiles(id) ON DELETE SET NULL not valid;

alter table "public"."profiles" validate constraint "profiles_manager_id_fkey";

alter table "public"."questions" add constraint "questions_exam_id_fkey" FOREIGN KEY (exam_id) REFERENCES public.exams(id) ON DELETE CASCADE not valid;

alter table "public"."questions" validate constraint "questions_exam_id_fkey";

alter table "public"."scores" add constraint "scores_exam_id_fkey" FOREIGN KEY (exam_id) REFERENCES public.exams(id) ON DELETE CASCADE not valid;

alter table "public"."scores" validate constraint "scores_exam_id_fkey";

alter table "public"."scores" add constraint "scores_exam_id_student_id_key" UNIQUE using index "scores_exam_id_student_id_key";

alter table "public"."scores" add constraint "scores_score_check" CHECK (((score >= (0)::numeric) AND (score <= (100)::numeric))) not valid;

alter table "public"."scores" validate constraint "scores_score_check";

alter table "public"."scores" add constraint "scores_student_id_fkey" FOREIGN KEY (student_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."scores" validate constraint "scores_student_id_fkey";

alter table "public"."student_answers" add constraint "student_answers_exam_id_fkey" FOREIGN KEY (exam_id) REFERENCES public.exams(id) ON DELETE CASCADE not valid;

alter table "public"."student_answers" validate constraint "student_answers_exam_id_fkey";

alter table "public"."student_answers" add constraint "student_answers_question_id_fkey" FOREIGN KEY (question_id) REFERENCES public.questions(id) ON DELETE CASCADE not valid;

alter table "public"."student_answers" validate constraint "student_answers_question_id_fkey";

alter table "public"."student_answers" add constraint "student_answers_student_id_fkey" FOREIGN KEY (student_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."student_answers" validate constraint "student_answers_student_id_fkey";

alter table "public"."subjects" add constraint "subjects_manager_id_fkey" FOREIGN KEY (manager_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."subjects" validate constraint "subjects_manager_id_fkey";

alter table "public"."subscriptions" add constraint "subscriptions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."subscriptions" validate constraint "subscriptions_user_id_fkey";

alter table "public"."subscriptions" add constraint "subscriptions_user_id_key" UNIQUE using index "subscriptions_user_id_key";

alter table "public"."task_feedback" add constraint "task_feedback_task_id_fkey" FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE not valid;

alter table "public"."task_feedback" validate constraint "task_feedback_task_id_fkey";

alter table "public"."task_feedback" add constraint "task_feedback_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."task_feedback" validate constraint "task_feedback_user_id_fkey";

alter table "public"."tasks" add constraint "tasks_class_id_fkey" FOREIGN KEY (class_id) REFERENCES public.classes(id) not valid;

alter table "public"."tasks" validate constraint "tasks_class_id_fkey";

alter table "public"."users" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."users" validate constraint "profiles_id_fkey";

set check_function_bodies = off;

create or replace view "public"."daily_pomodoro_stats" as  SELECT pomodoro_sessions.user_id,
    pomodoro_sessions.session_date,
    sum(
        CASE
            WHEN ((pomodoro_sessions.session_type = 'focus'::text) AND (pomodoro_sessions.completed = true)) THEN pomodoro_sessions.duration_minutes
            ELSE 0
        END) AS total_focus_minutes,
    count(
        CASE
            WHEN ((pomodoro_sessions.session_type = 'focus'::text) AND (pomodoro_sessions.completed = true)) THEN 1
            ELSE NULL::integer
        END) AS completed_pomodoros,
    count(
        CASE
            WHEN ((pomodoro_sessions.session_type = 'focus'::text) AND (pomodoro_sessions.completed = false)) THEN 1
            ELSE NULL::integer
        END) AS incomplete_pomodoros
   FROM public.pomodoro_sessions
  GROUP BY pomodoro_sessions.user_id, pomodoro_sessions.session_date;


CREATE OR REPLACE FUNCTION public.get_all_users_including_inactive()
 RETURNS SETOF auth.users
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  SELECT * FROM auth.users;
$function$
;

CREATE OR REPLACE FUNCTION public.get_my_claim(claim text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
AS $function$
  SELECT NULLIF(current_setting('request.jwt.claims', TRUE), '')::JSONB -> claim
$function$
;

CREATE OR REPLACE FUNCTION public.get_my_role()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT role FROM public.profiles WHERE id = auth.uid()
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_manager_id()
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN (SELECT manager_id FROM public.profiles WHERE id = auth.uid());
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_role()
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN (SELECT role FROM public.profiles WHERE id = auth.uid());
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    INSERT INTO public.profiles (id, username, name, email, avatar_url)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'username', NEW.email),
        COALESCE(NEW.raw_user_meta_data->>'name', NEW.email),
        NEW.email,
        NEW.raw_user_meta_data->>'avatar_url'
    );
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
    new.updated_at = now();
    return new;
end;
$function$
;

grant delete on table "public"."absentees" to "anon";

grant insert on table "public"."absentees" to "anon";

grant references on table "public"."absentees" to "anon";

grant select on table "public"."absentees" to "anon";

grant trigger on table "public"."absentees" to "anon";

grant truncate on table "public"."absentees" to "anon";

grant update on table "public"."absentees" to "anon";

grant delete on table "public"."absentees" to "authenticated";

grant insert on table "public"."absentees" to "authenticated";

grant references on table "public"."absentees" to "authenticated";

grant select on table "public"."absentees" to "authenticated";

grant trigger on table "public"."absentees" to "authenticated";

grant truncate on table "public"."absentees" to "authenticated";

grant update on table "public"."absentees" to "authenticated";

grant delete on table "public"."absentees" to "service_role";

grant insert on table "public"."absentees" to "service_role";

grant references on table "public"."absentees" to "service_role";

grant select on table "public"."absentees" to "service_role";

grant trigger on table "public"."absentees" to "service_role";

grant truncate on table "public"."absentees" to "service_role";

grant update on table "public"."absentees" to "service_role";

grant delete on table "public"."active_sessions" to "anon";

grant insert on table "public"."active_sessions" to "anon";

grant references on table "public"."active_sessions" to "anon";

grant select on table "public"."active_sessions" to "anon";

grant trigger on table "public"."active_sessions" to "anon";

grant truncate on table "public"."active_sessions" to "anon";

grant update on table "public"."active_sessions" to "anon";

grant delete on table "public"."active_sessions" to "authenticated";

grant insert on table "public"."active_sessions" to "authenticated";

grant references on table "public"."active_sessions" to "authenticated";

grant select on table "public"."active_sessions" to "authenticated";

grant trigger on table "public"."active_sessions" to "authenticated";

grant truncate on table "public"."active_sessions" to "authenticated";

grant update on table "public"."active_sessions" to "authenticated";

grant delete on table "public"."active_sessions" to "service_role";

grant insert on table "public"."active_sessions" to "service_role";

grant references on table "public"."active_sessions" to "service_role";

grant select on table "public"."active_sessions" to "service_role";

grant trigger on table "public"."active_sessions" to "service_role";

grant truncate on table "public"."active_sessions" to "service_role";

grant update on table "public"."active_sessions" to "service_role";

grant delete on table "public"."channel_members" to "anon";

grant insert on table "public"."channel_members" to "anon";

grant references on table "public"."channel_members" to "anon";

grant select on table "public"."channel_members" to "anon";

grant trigger on table "public"."channel_members" to "anon";

grant truncate on table "public"."channel_members" to "anon";

grant update on table "public"."channel_members" to "anon";

grant delete on table "public"."channel_members" to "authenticated";

grant insert on table "public"."channel_members" to "authenticated";

grant references on table "public"."channel_members" to "authenticated";

grant select on table "public"."channel_members" to "authenticated";

grant trigger on table "public"."channel_members" to "authenticated";

grant truncate on table "public"."channel_members" to "authenticated";

grant update on table "public"."channel_members" to "authenticated";

grant delete on table "public"."channel_members" to "service_role";

grant insert on table "public"."channel_members" to "service_role";

grant references on table "public"."channel_members" to "service_role";

grant select on table "public"."channel_members" to "service_role";

grant trigger on table "public"."channel_members" to "service_role";

grant truncate on table "public"."channel_members" to "service_role";

grant update on table "public"."channel_members" to "service_role";

grant delete on table "public"."channel_users" to "anon";

grant insert on table "public"."channel_users" to "anon";

grant references on table "public"."channel_users" to "anon";

grant select on table "public"."channel_users" to "anon";

grant trigger on table "public"."channel_users" to "anon";

grant truncate on table "public"."channel_users" to "anon";

grant update on table "public"."channel_users" to "anon";

grant delete on table "public"."channel_users" to "authenticated";

grant insert on table "public"."channel_users" to "authenticated";

grant references on table "public"."channel_users" to "authenticated";

grant select on table "public"."channel_users" to "authenticated";

grant trigger on table "public"."channel_users" to "authenticated";

grant truncate on table "public"."channel_users" to "authenticated";

grant update on table "public"."channel_users" to "authenticated";

grant delete on table "public"."channel_users" to "service_role";

grant insert on table "public"."channel_users" to "service_role";

grant references on table "public"."channel_users" to "service_role";

grant select on table "public"."channel_users" to "service_role";

grant trigger on table "public"."channel_users" to "service_role";

grant truncate on table "public"."channel_users" to "service_role";

grant update on table "public"."channel_users" to "service_role";

grant delete on table "public"."channels" to "anon";

grant insert on table "public"."channels" to "anon";

grant references on table "public"."channels" to "anon";

grant select on table "public"."channels" to "anon";

grant trigger on table "public"."channels" to "anon";

grant truncate on table "public"."channels" to "anon";

grant update on table "public"."channels" to "anon";

grant delete on table "public"."channels" to "authenticated";

grant insert on table "public"."channels" to "authenticated";

grant references on table "public"."channels" to "authenticated";

grant select on table "public"."channels" to "authenticated";

grant trigger on table "public"."channels" to "authenticated";

grant truncate on table "public"."channels" to "authenticated";

grant update on table "public"."channels" to "authenticated";

grant delete on table "public"."channels" to "service_role";

grant insert on table "public"."channels" to "service_role";

grant references on table "public"."channels" to "service_role";

grant select on table "public"."channels" to "service_role";

grant trigger on table "public"."channels" to "service_role";

grant truncate on table "public"."channels" to "service_role";

grant update on table "public"."channels" to "service_role";

grant delete on table "public"."classes" to "anon";

grant insert on table "public"."classes" to "anon";

grant references on table "public"."classes" to "anon";

grant select on table "public"."classes" to "anon";

grant trigger on table "public"."classes" to "anon";

grant truncate on table "public"."classes" to "anon";

grant update on table "public"."classes" to "anon";

grant delete on table "public"."classes" to "authenticated";

grant insert on table "public"."classes" to "authenticated";

grant references on table "public"."classes" to "authenticated";

grant select on table "public"."classes" to "authenticated";

grant trigger on table "public"."classes" to "authenticated";

grant truncate on table "public"."classes" to "authenticated";

grant update on table "public"."classes" to "authenticated";

grant delete on table "public"."classes" to "service_role";

grant insert on table "public"."classes" to "service_role";

grant references on table "public"."classes" to "service_role";

grant select on table "public"."classes" to "service_role";

grant trigger on table "public"."classes" to "service_role";

grant truncate on table "public"."classes" to "service_role";

grant update on table "public"."classes" to "service_role";

grant delete on table "public"."exam_attempts" to "anon";

grant insert on table "public"."exam_attempts" to "anon";

grant references on table "public"."exam_attempts" to "anon";

grant select on table "public"."exam_attempts" to "anon";

grant trigger on table "public"."exam_attempts" to "anon";

grant truncate on table "public"."exam_attempts" to "anon";

grant update on table "public"."exam_attempts" to "anon";

grant delete on table "public"."exam_attempts" to "authenticated";

grant insert on table "public"."exam_attempts" to "authenticated";

grant references on table "public"."exam_attempts" to "authenticated";

grant select on table "public"."exam_attempts" to "authenticated";

grant trigger on table "public"."exam_attempts" to "authenticated";

grant truncate on table "public"."exam_attempts" to "authenticated";

grant update on table "public"."exam_attempts" to "authenticated";

grant delete on table "public"."exam_attempts" to "service_role";

grant insert on table "public"."exam_attempts" to "service_role";

grant references on table "public"."exam_attempts" to "service_role";

grant select on table "public"."exam_attempts" to "service_role";

grant trigger on table "public"."exam_attempts" to "service_role";

grant truncate on table "public"."exam_attempts" to "service_role";

grant update on table "public"."exam_attempts" to "service_role";

grant delete on table "public"."exams" to "anon";

grant insert on table "public"."exams" to "anon";

grant references on table "public"."exams" to "anon";

grant select on table "public"."exams" to "anon";

grant trigger on table "public"."exams" to "anon";

grant truncate on table "public"."exams" to "anon";

grant update on table "public"."exams" to "anon";

grant delete on table "public"."exams" to "authenticated";

grant insert on table "public"."exams" to "authenticated";

grant references on table "public"."exams" to "authenticated";

grant select on table "public"."exams" to "authenticated";

grant trigger on table "public"."exams" to "authenticated";

grant truncate on table "public"."exams" to "authenticated";

grant update on table "public"."exams" to "authenticated";

grant delete on table "public"."exams" to "service_role";

grant insert on table "public"."exams" to "service_role";

grant references on table "public"."exams" to "service_role";

grant select on table "public"."exams" to "service_role";

grant trigger on table "public"."exams" to "service_role";

grant truncate on table "public"."exams" to "service_role";

grant update on table "public"."exams" to "service_role";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant references on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant references on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";

grant delete on table "public"."online_sessions" to "anon";

grant insert on table "public"."online_sessions" to "anon";

grant references on table "public"."online_sessions" to "anon";

grant select on table "public"."online_sessions" to "anon";

grant trigger on table "public"."online_sessions" to "anon";

grant truncate on table "public"."online_sessions" to "anon";

grant update on table "public"."online_sessions" to "anon";

grant delete on table "public"."online_sessions" to "authenticated";

grant insert on table "public"."online_sessions" to "authenticated";

grant references on table "public"."online_sessions" to "authenticated";

grant select on table "public"."online_sessions" to "authenticated";

grant trigger on table "public"."online_sessions" to "authenticated";

grant truncate on table "public"."online_sessions" to "authenticated";

grant update on table "public"."online_sessions" to "authenticated";

grant delete on table "public"."online_sessions" to "service_role";

grant insert on table "public"."online_sessions" to "service_role";

grant references on table "public"."online_sessions" to "service_role";

grant select on table "public"."online_sessions" to "service_role";

grant trigger on table "public"."online_sessions" to "service_role";

grant truncate on table "public"."online_sessions" to "service_role";

grant update on table "public"."online_sessions" to "service_role";

grant delete on table "public"."pomodoro_sessions" to "anon";

grant insert on table "public"."pomodoro_sessions" to "anon";

grant references on table "public"."pomodoro_sessions" to "anon";

grant select on table "public"."pomodoro_sessions" to "anon";

grant trigger on table "public"."pomodoro_sessions" to "anon";

grant truncate on table "public"."pomodoro_sessions" to "anon";

grant update on table "public"."pomodoro_sessions" to "anon";

grant delete on table "public"."pomodoro_sessions" to "authenticated";

grant insert on table "public"."pomodoro_sessions" to "authenticated";

grant references on table "public"."pomodoro_sessions" to "authenticated";

grant select on table "public"."pomodoro_sessions" to "authenticated";

grant trigger on table "public"."pomodoro_sessions" to "authenticated";

grant truncate on table "public"."pomodoro_sessions" to "authenticated";

grant update on table "public"."pomodoro_sessions" to "authenticated";

grant delete on table "public"."pomodoro_sessions" to "service_role";

grant insert on table "public"."pomodoro_sessions" to "service_role";

grant references on table "public"."pomodoro_sessions" to "service_role";

grant select on table "public"."pomodoro_sessions" to "service_role";

grant trigger on table "public"."pomodoro_sessions" to "service_role";

grant truncate on table "public"."pomodoro_sessions" to "service_role";

grant update on table "public"."pomodoro_sessions" to "service_role";

grant delete on table "public"."presence_checks" to "anon";

grant insert on table "public"."presence_checks" to "anon";

grant references on table "public"."presence_checks" to "anon";

grant select on table "public"."presence_checks" to "anon";

grant trigger on table "public"."presence_checks" to "anon";

grant truncate on table "public"."presence_checks" to "anon";

grant update on table "public"."presence_checks" to "anon";

grant delete on table "public"."presence_checks" to "authenticated";

grant insert on table "public"."presence_checks" to "authenticated";

grant references on table "public"."presence_checks" to "authenticated";

grant select on table "public"."presence_checks" to "authenticated";

grant trigger on table "public"."presence_checks" to "authenticated";

grant truncate on table "public"."presence_checks" to "authenticated";

grant update on table "public"."presence_checks" to "authenticated";

grant delete on table "public"."presence_checks" to "service_role";

grant insert on table "public"."presence_checks" to "service_role";

grant references on table "public"."presence_checks" to "service_role";

grant select on table "public"."presence_checks" to "service_role";

grant trigger on table "public"."presence_checks" to "service_role";

grant truncate on table "public"."presence_checks" to "service_role";

grant update on table "public"."presence_checks" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."questions" to "anon";

grant insert on table "public"."questions" to "anon";

grant references on table "public"."questions" to "anon";

grant select on table "public"."questions" to "anon";

grant trigger on table "public"."questions" to "anon";

grant truncate on table "public"."questions" to "anon";

grant update on table "public"."questions" to "anon";

grant delete on table "public"."questions" to "authenticated";

grant insert on table "public"."questions" to "authenticated";

grant references on table "public"."questions" to "authenticated";

grant select on table "public"."questions" to "authenticated";

grant trigger on table "public"."questions" to "authenticated";

grant truncate on table "public"."questions" to "authenticated";

grant update on table "public"."questions" to "authenticated";

grant delete on table "public"."questions" to "service_role";

grant insert on table "public"."questions" to "service_role";

grant references on table "public"."questions" to "service_role";

grant select on table "public"."questions" to "service_role";

grant trigger on table "public"."questions" to "service_role";

grant truncate on table "public"."questions" to "service_role";

grant update on table "public"."questions" to "service_role";

grant delete on table "public"."scores" to "anon";

grant insert on table "public"."scores" to "anon";

grant references on table "public"."scores" to "anon";

grant select on table "public"."scores" to "anon";

grant trigger on table "public"."scores" to "anon";

grant truncate on table "public"."scores" to "anon";

grant update on table "public"."scores" to "anon";

grant delete on table "public"."scores" to "authenticated";

grant insert on table "public"."scores" to "authenticated";

grant references on table "public"."scores" to "authenticated";

grant select on table "public"."scores" to "authenticated";

grant trigger on table "public"."scores" to "authenticated";

grant truncate on table "public"."scores" to "authenticated";

grant update on table "public"."scores" to "authenticated";

grant delete on table "public"."scores" to "service_role";

grant insert on table "public"."scores" to "service_role";

grant references on table "public"."scores" to "service_role";

grant select on table "public"."scores" to "service_role";

grant trigger on table "public"."scores" to "service_role";

grant truncate on table "public"."scores" to "service_role";

grant update on table "public"."scores" to "service_role";

grant delete on table "public"."settings" to "anon";

grant insert on table "public"."settings" to "anon";

grant references on table "public"."settings" to "anon";

grant select on table "public"."settings" to "anon";

grant trigger on table "public"."settings" to "anon";

grant truncate on table "public"."settings" to "anon";

grant update on table "public"."settings" to "anon";

grant delete on table "public"."settings" to "authenticated";

grant insert on table "public"."settings" to "authenticated";

grant references on table "public"."settings" to "authenticated";

grant select on table "public"."settings" to "authenticated";

grant trigger on table "public"."settings" to "authenticated";

grant truncate on table "public"."settings" to "authenticated";

grant update on table "public"."settings" to "authenticated";

grant delete on table "public"."settings" to "service_role";

grant insert on table "public"."settings" to "service_role";

grant references on table "public"."settings" to "service_role";

grant select on table "public"."settings" to "service_role";

grant trigger on table "public"."settings" to "service_role";

grant truncate on table "public"."settings" to "service_role";

grant update on table "public"."settings" to "service_role";

grant delete on table "public"."student_answers" to "anon";

grant insert on table "public"."student_answers" to "anon";

grant references on table "public"."student_answers" to "anon";

grant select on table "public"."student_answers" to "anon";

grant trigger on table "public"."student_answers" to "anon";

grant truncate on table "public"."student_answers" to "anon";

grant update on table "public"."student_answers" to "anon";

grant delete on table "public"."student_answers" to "authenticated";

grant insert on table "public"."student_answers" to "authenticated";

grant references on table "public"."student_answers" to "authenticated";

grant select on table "public"."student_answers" to "authenticated";

grant trigger on table "public"."student_answers" to "authenticated";

grant truncate on table "public"."student_answers" to "authenticated";

grant update on table "public"."student_answers" to "authenticated";

grant delete on table "public"."student_answers" to "service_role";

grant insert on table "public"."student_answers" to "service_role";

grant references on table "public"."student_answers" to "service_role";

grant select on table "public"."student_answers" to "service_role";

grant trigger on table "public"."student_answers" to "service_role";

grant truncate on table "public"."student_answers" to "service_role";

grant update on table "public"."student_answers" to "service_role";

grant delete on table "public"."subjects" to "anon";

grant insert on table "public"."subjects" to "anon";

grant references on table "public"."subjects" to "anon";

grant select on table "public"."subjects" to "anon";

grant trigger on table "public"."subjects" to "anon";

grant truncate on table "public"."subjects" to "anon";

grant update on table "public"."subjects" to "anon";

grant delete on table "public"."subjects" to "authenticated";

grant insert on table "public"."subjects" to "authenticated";

grant references on table "public"."subjects" to "authenticated";

grant select on table "public"."subjects" to "authenticated";

grant trigger on table "public"."subjects" to "authenticated";

grant truncate on table "public"."subjects" to "authenticated";

grant update on table "public"."subjects" to "authenticated";

grant delete on table "public"."subjects" to "service_role";

grant insert on table "public"."subjects" to "service_role";

grant references on table "public"."subjects" to "service_role";

grant select on table "public"."subjects" to "service_role";

grant trigger on table "public"."subjects" to "service_role";

grant truncate on table "public"."subjects" to "service_role";

grant update on table "public"."subjects" to "service_role";

grant delete on table "public"."subscriptions" to "anon";

grant insert on table "public"."subscriptions" to "anon";

grant references on table "public"."subscriptions" to "anon";

grant select on table "public"."subscriptions" to "anon";

grant trigger on table "public"."subscriptions" to "anon";

grant truncate on table "public"."subscriptions" to "anon";

grant update on table "public"."subscriptions" to "anon";

grant delete on table "public"."subscriptions" to "authenticated";

grant insert on table "public"."subscriptions" to "authenticated";

grant references on table "public"."subscriptions" to "authenticated";

grant select on table "public"."subscriptions" to "authenticated";

grant trigger on table "public"."subscriptions" to "authenticated";

grant truncate on table "public"."subscriptions" to "authenticated";

grant update on table "public"."subscriptions" to "authenticated";

grant delete on table "public"."subscriptions" to "service_role";

grant insert on table "public"."subscriptions" to "service_role";

grant references on table "public"."subscriptions" to "service_role";

grant select on table "public"."subscriptions" to "service_role";

grant trigger on table "public"."subscriptions" to "service_role";

grant truncate on table "public"."subscriptions" to "service_role";

grant update on table "public"."subscriptions" to "service_role";

grant delete on table "public"."task_feedback" to "anon";

grant insert on table "public"."task_feedback" to "anon";

grant references on table "public"."task_feedback" to "anon";

grant select on table "public"."task_feedback" to "anon";

grant trigger on table "public"."task_feedback" to "anon";

grant truncate on table "public"."task_feedback" to "anon";

grant update on table "public"."task_feedback" to "anon";

grant delete on table "public"."task_feedback" to "authenticated";

grant insert on table "public"."task_feedback" to "authenticated";

grant references on table "public"."task_feedback" to "authenticated";

grant select on table "public"."task_feedback" to "authenticated";

grant trigger on table "public"."task_feedback" to "authenticated";

grant truncate on table "public"."task_feedback" to "authenticated";

grant update on table "public"."task_feedback" to "authenticated";

grant delete on table "public"."task_feedback" to "service_role";

grant insert on table "public"."task_feedback" to "service_role";

grant references on table "public"."task_feedback" to "service_role";

grant select on table "public"."task_feedback" to "service_role";

grant trigger on table "public"."task_feedback" to "service_role";

grant truncate on table "public"."task_feedback" to "service_role";

grant update on table "public"."task_feedback" to "service_role";

grant delete on table "public"."tasks" to "anon";

grant insert on table "public"."tasks" to "anon";

grant references on table "public"."tasks" to "anon";

grant select on table "public"."tasks" to "anon";

grant trigger on table "public"."tasks" to "anon";

grant truncate on table "public"."tasks" to "anon";

grant update on table "public"."tasks" to "anon";

grant delete on table "public"."tasks" to "authenticated";

grant insert on table "public"."tasks" to "authenticated";

grant references on table "public"."tasks" to "authenticated";

grant select on table "public"."tasks" to "authenticated";

grant trigger on table "public"."tasks" to "authenticated";

grant truncate on table "public"."tasks" to "authenticated";

grant update on table "public"."tasks" to "authenticated";

grant delete on table "public"."tasks" to "service_role";

grant insert on table "public"."tasks" to "service_role";

grant references on table "public"."tasks" to "service_role";

grant select on table "public"."tasks" to "service_role";

grant trigger on table "public"."tasks" to "service_role";

grant truncate on table "public"."tasks" to "service_role";

grant update on table "public"."tasks" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";


  create policy "Allow authenticated users to read absentee list"
  on "public"."absentees"
  as permissive
  for select
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Allow teachers/admins to manage absentee list"
  on "public"."absentees"
  as permissive
  for all
  to public
using ((( SELECT profiles.role
   FROM public.profiles
  WHERE (profiles.id = auth.uid())) = ANY (ARRAY['admin'::text, 'teacher'::text, 'consultant'::text])));



  create policy "Enable all actions for students on their own sessions"
  on "public"."active_sessions"
  as permissive
  for all
  to public
using ((auth.uid() = student_id));



  create policy "Anyone can read channels"
  on "public"."channels"
  as permissive
  for select
  to public
using (true);



  create policy "Authenticated users can create channels"
  on "public"."channels"
  as permissive
  for insert
  to public
with check ((auth.role() = 'authenticated'::text));



  create policy "Allow all access for authenticated users on classes"
  on "public"."classes"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Allow authenticated users to read classes"
  on "public"."classes"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Allow managers to delete their own classes"
  on "public"."classes"
  as permissive
  for delete
  to authenticated
using (((manager_id = ( SELECT profiles.manager_id
   FROM public.profiles
  WHERE (profiles.id = auth.uid()))) OR (manager_id = auth.uid())));



  create policy "Allow managers to insert their own classes"
  on "public"."classes"
  as permissive
  for insert
  to authenticated
with check (((manager_id = ( SELECT profiles.manager_id
   FROM public.profiles
  WHERE (profiles.id = auth.uid()))) OR (manager_id = auth.uid())));



  create policy "Allow managers to update their own classes"
  on "public"."classes"
  as permissive
  for update
  to authenticated
using (((manager_id = ( SELECT profiles.manager_id
   FROM public.profiles
  WHERE (profiles.id = auth.uid()))) OR (manager_id = auth.uid())));



  create policy "Staff can view attempts from their school's students"
  on "public"."exam_attempts"
  as permissive
  for select
  to public
using (((( SELECT profiles.manager_id
   FROM public.profiles
  WHERE (profiles.id = exam_attempts.student_id)) = ( SELECT profiles.manager_id
   FROM public.profiles
  WHERE (profiles.id = auth.uid()))) OR (( SELECT profiles.manager_id
   FROM public.profiles
  WHERE (profiles.id = exam_attempts.student_id)) = auth.uid())));



  create policy "Students can manage their own exam attempts"
  on "public"."exam_attempts"
  as permissive
  for all
  to public
using ((auth.uid() = student_id));



  create policy "Students can start their own exam attempts"
  on "public"."exam_attempts"
  as permissive
  for insert
  to public
with check ((auth.uid() = student_id));



  create policy "Students can view their own exam attempts"
  on "public"."exam_attempts"
  as permissive
  for select
  to public
using ((auth.uid() = student_id));



  create policy "Allow all access for authenticated users on exams"
  on "public"."exams"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Anyone can read messages"
  on "public"."messages"
  as permissive
  for select
  to public
using (true);



  create policy "Everyone can insert messages"
  on "public"."messages"
  as permissive
  for insert
  to public
with check (true);



  create policy "Allow managers to delete their own sessions"
  on "public"."online_sessions"
  as permissive
  for delete
  to authenticated
using (((manager_id = ( SELECT profiles.manager_id
   FROM public.profiles
  WHERE (profiles.id = auth.uid()))) OR (manager_id = auth.uid())));



  create policy "Allow managers to insert their own sessions"
  on "public"."online_sessions"
  as permissive
  for insert
  to authenticated
with check (((manager_id = ( SELECT profiles.manager_id
   FROM public.profiles
  WHERE (profiles.id = auth.uid()))) OR (manager_id = auth.uid())));



  create policy "Allow managers to update their own sessions"
  on "public"."online_sessions"
  as permissive
  for update
  to authenticated
using (((manager_id = ( SELECT profiles.manager_id
   FROM public.profiles
  WHERE (profiles.id = auth.uid()))) OR (manager_id = auth.uid())));



  create policy "Enable read access for relevant users"
  on "public"."online_sessions"
  as permissive
  for select
  to authenticated
using (((class_id = ( SELECT profiles.class_id
   FROM public.profiles
  WHERE (profiles.id = auth.uid()))) OR (manager_id = ( SELECT profiles.manager_id
   FROM public.profiles
  WHERE (profiles.id = auth.uid()))) OR (manager_id = auth.uid())));



  create policy "Users can insert their own sessions"
  on "public"."pomodoro_sessions"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can update their own sessions"
  on "public"."pomodoro_sessions"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "Users can view their own sessions"
  on "public"."pomodoro_sessions"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Students can insert their own entry record"
  on "public"."presence_checks"
  as permissive
  for insert
  to public
with check ((auth.uid() = student_id));



  create policy "Students can update their own presence check"
  on "public"."presence_checks"
  as permissive
  for update
  to public
using ((auth.uid() = student_id))
with check ((auth.uid() = student_id));



  create policy "Teachers can initiate presence checks"
  on "public"."presence_checks"
  as permissive
  for insert
  to authenticated
with check (((is_entry = false) AND (EXISTS ( SELECT 1
   FROM public.online_sessions
  WHERE ((online_sessions.id = presence_checks.session_id) AND ((online_sessions.created_by = auth.uid()) OR (online_sessions.manager_id = auth.uid())))))));



  create policy "Users can read presence data"
  on "public"."presence_checks"
  as permissive
  for select
  to public
using (((auth.uid() = student_id) OR (((public.get_my_claim('role'::text) = ANY (ARRAY['"admin"'::jsonb, '"teacher"'::jsonb, '"consultant"'::jsonb])) AND (EXISTS ( SELECT 1
   FROM public.online_sessions
  WHERE ((online_sessions.id = presence_checks.session_id) AND (online_sessions.manager_id = ( SELECT profiles.manager_id
           FROM public.profiles
          WHERE (profiles.id = auth.uid()))))))) OR (EXISTS ( SELECT 1
   FROM public.online_sessions
  WHERE ((online_sessions.id = presence_checks.session_id) AND (online_sessions.manager_id = auth.uid())))))));



  create policy "Allow profile read access"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using (((auth.uid() = id) OR (manager_id = auth.uid()) OR (public.get_my_role() = ANY (ARRAY['super_admin'::text, 'admin'::text, 'teacher'::text, 'consultant'::text]))));



  create policy "Allow profile update access"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using (((auth.uid() = id) OR ((public.get_my_role() = ANY (ARRAY['admin'::text, 'teacher'::text, 'consultant'::text])) AND (manager_id = auth.uid()))))
with check (((auth.uid() = id) OR ((public.get_my_role() = ANY (ARRAY['admin'::text, 'teacher'::text, 'consultant'::text])) AND (manager_id = auth.uid()))));



  create policy "Allow all access for authenticated users on questions"
  on "public"."questions"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Admins, Teachers, and Consultants can manage scores"
  on "public"."scores"
  as permissive
  for all
  to authenticated
using ((public.get_user_role() = ANY (ARRAY['admin'::text, 'teacher'::text, 'consultant'::text])))
with check ((public.get_user_role() = ANY (ARRAY['admin'::text, 'teacher'::text, 'consultant'::text])));



  create policy "Admins, Teachers, and Consultants can view all scores"
  on "public"."scores"
  as permissive
  for select
  to authenticated
using ((public.get_user_role() = ANY (ARRAY['admin'::text, 'teacher'::text, 'consultant'::text])));



  create policy "Students can view their own scores"
  on "public"."scores"
  as permissive
  for select
  to authenticated
using ((auth.uid() = student_id));



  create policy "Staff can view answers for their school's students"
  on "public"."student_answers"
  as permissive
  for select
  to public
using ((( SELECT profiles.manager_id
   FROM public.profiles
  WHERE (auth.uid() = profiles.id)) = ( SELECT profiles.manager_id
   FROM public.profiles
  WHERE (profiles.id = student_answers.student_id))));



  create policy "Students can manage their own answers"
  on "public"."student_answers"
  as permissive
  for all
  to public
using ((auth.uid() = student_id));



  create policy "Students can submit answers for their own exams"
  on "public"."student_answers"
  as permissive
  for insert
  to public
with check ((auth.uid() = student_id));



  create policy "Admins can manage subjects"
  on "public"."subjects"
  as permissive
  for all
  to authenticated
using ((public.get_user_role() = 'admin'::text))
with check ((public.get_user_role() = 'admin'::text));



  create policy "Allow all access for authenticated users on subjects"
  on "public"."subjects"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Authenticated users can view subjects"
  on "public"."subjects"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Users can insert their own feedback"
  on "public"."task_feedback"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can view their own feedback"
  on "public"."task_feedback"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Simple tasks policy"
  on "public"."tasks"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Users can create tasks"
  on "public"."tasks"
  as permissive
  for insert
  to public
with check (((auth.uid())::text = user_id));



  create policy "Users can delete their own tasks"
  on "public"."tasks"
  as permissive
  for delete
  to public
using (((auth.uid())::text = user_id));



  create policy "Users can update their own tasks"
  on "public"."tasks"
  as permissive
  for update
  to public
using (((auth.uid())::text = user_id))
with check (((auth.uid())::text = user_id));



  create policy "Users can view their own tasks"
  on "public"."tasks"
  as permissive
  for select
  to public
using (((auth.uid())::text = user_id));



  create policy "allow "
  on "public"."tasks"
  as permissive
  for all
  to public
using (true)
with check (true);



  create policy "Users can delete their own profile"
  on "public"."users"
  as permissive
  for delete
  to public
using ((auth.uid() = id));



  create policy "Users can insert their own profile"
  on "public"."users"
  as permissive
  for insert
  to public
with check ((auth.uid() = id));



  create policy "Users can read their own data"
  on "public"."users"
  as permissive
  for select
  to public
using ((auth.uid() = id));



  create policy "Users can update their own data"
  on "public"."users"
  as permissive
  for update
  to public
using ((auth.uid() = id))
with check ((auth.uid() = id));


CREATE TRIGGER update_pomodoro_sessions_updated_at BEFORE UPDATE ON public.pomodoro_sessions FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "Allow staff to manage question images"
  on "storage"."objects"
  as permissive
  for all
  to authenticated
using (((bucket_id = 'question_images'::text) AND (( SELECT profiles.role
   FROM public.profiles
  WHERE (profiles.id = auth.uid())) = ANY (ARRAY['admin'::text, 'teacher'::text, 'consultant'::text, 'super_admin'::text]))));



  create policy "Anyone can view avatars"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'uesr'::text));



  create policy "Users can upload their own avatar"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'uesr'::text));



  create policy "spooderimagespublic 2ooc87_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'spooderimage'::text));



  create policy "spooderimagespublic 2ooc87_1"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'spooderimage'::text));



  create policy "spooderimagespublic 2ooc87_2"
  on "storage"."objects"
  as permissive
  for update
  to public
using ((bucket_id = 'spooderimage'::text));



  create policy "spooderimagespublic 2ooc87_3"
  on "storage"."objects"
  as permissive
  for delete
  to public
using ((bucket_id = 'spooderimage'::text));



